namespace: poolwatch

poolwatch:
  database: mongodb://mongo-production-service.poolwatch.svc.cluster.local
  deviceHostname: device.necrass
  hostname: poolswatch.com
  image: repo.necrass/poolwatch:1.2.1
  tlsSecret: necrass-tls
  dcTimeout: 60000
  sampleCheckRate: 60000

mongodb:
  image: docker.io/mongo:6
  node: necrass
  storage: 10Gi

emailSecret: emailcred