namespace: poolwatch

poolwatch:
  image: repo.skadi/poolwatch:1.3.0
  hostname: test.skadi
  deviceHostname: device.skadi
  database: mongodb://mongo-production-service.poolwatch.svc.cluster.local
  tlsSecret: skaditls-secret
  dcTimeout: 300000
  sampleCheckRate: 5000

mongodb:
  image: repo.skadi/mongo:6
  storage: 10Gi
  node: skadi

emailSecret: emailcred